Traceback (most recent call last):
  File "C:\Users\skorczewskit\Anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\skorczewskit\Anaconda3\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\skorczewskit\Anaconda3\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\skorczewskit\Anaconda3\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\skorczewskit\Anaconda3\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\skorczewskit\Anaconda3\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\skorczewskit\Anaconda3\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\skorczewskit\Anaconda3\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
v = np.array([0.,2.,4.,6.,8.,10.])
D = np.array([0.,2.9,14.8,39.6,74.3,119.])

vs = np.linspace(0,10,101)
Ds = 1.30625*vs**2 - 1.1625*vs

newDs = myLagrangeInterp(vs,v,D)

plt.plot(vs,Ds,"r:");
plt.plot(vs,newDs,'b--');
plt.plot(v,D,'kD');

plt.xlabel('vel (x10 ft/s)');
plt.ylabel('Drag (lbs0)');
plt.legend(['quadratic fit','quintic fit','data']);
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
Input [1;32mIn [8][0m, in [0;36m<cell line: 7>[1;34m()[0m
[0;32m      4[0m vs [38;5;241m=[39m np[38;5;241m.[39mlinspace([38;5;241m0[39m,[38;5;241m10[39m,[38;5;241m101[39m)
[0;32m      5[0m Ds [38;5;241m=[39m [38;5;241m1.30625[39m[38;5;241m*[39mvs[38;5;241m*[39m[38;5;241m*[39m[38;5;241m2[39m [38;5;241m-[39m [38;5;241m1.1625[39m[38;5;241m*[39mvs
[1;32m----> 7[0m newDs [38;5;241m=[39m [43mmyLagrangeInterp[49m(vs,v,D)
[0;32m      9[0m plt[38;5;241m.[39mplot(vs,Ds,[38;5;124m"[39m[38;5;124mr:[39m[38;5;124m"[39m);
[0;32m     10[0m plt[38;5;241m.[39mplot(vs,newDs,[38;5;124m'[39m[38;5;124mb--[39m[38;5;124m'[39m);

[1;31mNameError[0m: name 'myLagrangeInterp' is not defined
NameError: name 'myLagrangeInterp' is not defined

