Traceback (most recent call last):
  File "C:\Users\skorczewskit\Anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\skorczewskit\Anaconda3\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\skorczewskit\Anaconda3\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\skorczewskit\Anaconda3\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\skorczewskit\Anaconda3\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\skorczewskit\Anaconda3\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\skorczewskit\Anaconda3\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\skorczewskit\Anaconda3\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import csv
games = []
with open('../nfcnorth202021.csv', newline='') as f:
    reader = csv.reader(f, delimiter=',', quoting=csv.QUOTE_NONE)
    header=next(reader,None)
    print(header[5:])
    for game in reader:
        print(game[5:])
        games.append(game[5:])


------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mFileNotFoundError[0m                         Traceback (most recent call last)
Input [1;32mIn [2][0m, in [0;36m<cell line: 3>[1;34m()[0m
[0;32m      1[0m [38;5;28;01mimport[39;00m [38;5;21;01mcsv[39;00m
[0;32m      2[0m games [38;5;241m=[39m []
[1;32m----> 3[0m [38;5;28;01mwith[39;00m [38;5;28;43mopen[39;49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43m../nfcnorth202021.csv[39;49m[38;5;124;43m'[39;49m[43m,[49m[43m [49m[43mnewline[49m[38;5;241;43m=[39;49m[38;5;124;43m'[39;49m[38;5;124;43m'[39;49m[43m)[49m [38;5;28;01mas[39;00m f:
[0;32m      4[0m     reader [38;5;241m=[39m csv[38;5;241m.[39mreader(f, delimiter[38;5;241m=[39m[38;5;124m'[39m[38;5;124m,[39m[38;5;124m'[39m, quoting[38;5;241m=[39mcsv[38;5;241m.[39mQUOTE_NONE)
[0;32m      5[0m     header[38;5;241m=[39m[38;5;28mnext[39m(reader,[38;5;28;01mNone[39;00m)

[1;31mFileNotFoundError[0m: [Errno 2] No such file or directory: '../nfcnorth202021.csv'
FileNotFoundError: [Errno 2] No such file or directory: '../nfcnorth202021.csv'

